apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secrets
  namespace: payments
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    STRIPE_API_KEY: AgA34234b3...<redacted_encrypted_blob>...==
    DB_PASSWORD: AgA8948293...<redacted_encrypted_blob>...==
  template:
    metadata:
      name: ledger-api-secrets
      namespace: payments
    type: Opaque
